### PR TITLE
README: fix typo

### PR DESCRIPTION
**Pull request by birdayz**

### CODE REVIEW

**Comment by jasonkeene** [comment]
LGTM but I no longer have the merge button on this repo 😞

**Comment by MasslessParticle** [comment]
@birdayz We're happy to make this change in lieu of you signing the CLA if that's preferable

**Comment by birdayz** [comment]
sorry for the noise, i dont feel like hand signing a pdf and scanning it, emailing it, just to sign a cla - for a typo. was bot aware of this archaic process.

**Comment by jtuchscherer** [comment]
@birdayz  do you want us to do the change for you? You would not get the contribution, though.

**Pull request closed without merging**
